FROM debian/jessie

RUN apt-get update 
RUN apt-get install make

COPY prerequisities.sh /prerequisities.sh
RUN /prerequisities.sh

COPY deployment.tar.gz /opt/deployment.tar.gz
RUN cd /opt && tar xvfz deployment.tar.gz

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN mkdir -p /opt/test-config/group_vars
COPY test-config/inventory /opt/test-config
COPY test-config/infra-common /opt/test-config/group_vars
COPY ansible.cfg  /opt/ansible.cfg

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

